참고 : https://github.com/H2O-500ml/ADP/blob/master/03_Python_%EA%B8%B0%EC%B4%88%EC%A0%95%EB%A6%AC.ipynb

In [ ]:
# 워킹 디렉토리 확인
import os
os.getcwd()

'/content'

In [ ]:
# 메모리 리셋
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [ ]:
import pandas as pd

# 객체 속성 및 매소드 정보 확인
dir(pd)

# 함수 사용법 확인
help(int)

In [ ]:
# 도움말 찾기
a = 'string' 
dir(a) # a라는 변수에 쓸 수 있는 매소드 조회

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [ ]:
# a 변수에 upper method 설명
help(a.upper)

Help on built-in function upper:

upper() method of builtins.str instance
    Return a copy of the string converted to uppercase.



기본 분석 환경 세팅

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# print를 하지 않아도 행을 모두 보여줌
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivy = 'all'

In [ ]:
# columns 를 생략없이 모두 보여줌
from IPython.display import display
pd.options.display.max_columns = None

In [ ]:
# 한글 표기 
%matplotlib inline
import platform

from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

# 시스템 OS이름을 반환. 값을 판별할 수 없으면 빈 문자열 반환
# Linux : 리눅스, Darwin : 맥, Windows : 윈도우
if platform.system() == 'Darwin':
  rc('font',family = 'AppleGothic')
elif platform.system() == 'Windows':
  path = 'C:/Windows/Fonts/malgun.ttf'
  font_name = font_manager.FontProperties(fname = path).get_name()
  rc('font',family = font_name)
else : 
  print('Unknown System')

Unknown System


In [ ]:
platform.system() # gkggkt

'Linux'

파일읽기

In [ ]:
# read_csv : csv, tsv, txt
pd.read_csv('경로 / 파일이름.csv', encoding = 'cp949')
## params 
# header = True : 변수명 있을 시 불러옴
# naems = [~] : 변수명 직접추가
# encoding : cp949, utf-8, euc-kr
# sep = ''
# 경우에 따라 engin = 'python'
# skipinitialspace = True : 구분자 양쪽 공백 제거

# tsv read의 경우 delimiter = '\t'

# to_csv
df.to_csv('경로/파일이름.csv', header = True, index=False, encoding='cp949')

In [ ]:
# 확장자가 h5인 경우 - 시계열데이터일 경우가 있음 

# read_hdf
pd.read_hdf('파일이름.h5',key = '기준컬럼').set_index('날짜형식_컬럼').sort_index()

In [ ]:
# 기본 open

# 읽기
f = open('textfile.txt','r') # read mode
data = f.read()
f.close()

# 쓰기
f = open('textfile-copy.txt','w')
f.write(data)
f.close()

In [ ]:
# Pickle 활용

import pickle

# 저장 - Dump
data = ['a','b','c']
with open('pickle.txt','wb') as f :   # pickle의 경우 모드 뒤에 b를 붙여줘야 함
  pickle.dump(data,f)

# 불러오기 - Load
with open('pickle.txt','rb') as f:
  data = pickle.load(f) # 한줄씩 읽어옴
data

numpy

In [1]:
import numpy as np

# array 생성
a = np.array([1,2,3,4])

# array 생성의 여러 예
b = np.zeros((3,3)) # 0으로 된 3*3행렬
print('b', b)

c = np.ones((2,2)) # 1로 된 2*2 행렬
print('c',c)

d = np.full((2,2),7) # 특정 숫자로 채워진 2*2행렬
print('d',d)

e = np.eye(3,3) # 단위행렬
print('e',e)

f = np.random.random((2,2))
print('f',f)

g = np.arange(5)
print('g',g)

b [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
c [[1. 1.]
 [1. 1.]]
d [[7 7]
 [7 7]]
e [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
f [[0.41815727 0.17439821]
 [0.52678509 0.22155421]]
g [0 1 2 3 4]


In [2]:
# reshape
a = np.array([[1,2,3],[4,5,6]])
print('a',a)
a = a.reshape(3,2)
print('a_reshaped',a)
a = a.reshape(6,-1)
print('a_reshaped2',a)

a [[1 2 3]
 [4 5 6]]
a_reshaped [[1 2]
 [3 4]
 [5 6]]
a_reshaped2 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [4]:
# slice
print(d[0,:]) # 정수 슬라이싱 : 배열 차원 감소
print(d[0:1,:]) # 그냥 슬라이싱 : 배열 차원 유지
d.copy() # 배열 복사

[7 7]
[[7 7]]


array([[7, 7],
       [7, 7]])

In [5]:
# 숫자 다루기
import math

a = np.array([math.e,2,3])
# 절대값
np.abs(a)
# 제곱근
np.sqrt(a)
# 로그
np.log(a)
# 내림
np.floor(a)
# 올림
np.ceil(a)
# 반올림
np.rint(a)

array([3., 2., 3.])

pandas

In [7]:
import pandas as pd
data = {'name': ['Jason', 'Molly', np.nan, 'Jake', 'Amy'], 
        'year': [2012, 2012, 2013, 2014, 2014], 
        'reports': [4, 24, 31, 2, 3]}

df = pd.DataFrame(data, index = ['Cochice','Pima','Santa Cruz','Maricopa','Yuma'])
df

name  year  reports
Cochice     Jason  2012        4
Pima        Molly  2012       24
Santa Cruz    NaN  2013       31
Maricopa     Jake  2014        2
Yuma          Amy  2014        3

In [11]:
# 컬럼 이름 변경
df = df.rename(columns = {'name':'first_name'})
df

first_name  year  reports
Cochice         Jason  2012        4
Pima            Molly  2012       24
Santa Cruz        NaN  2013       31
Maricopa         Jake  2014        2
Yuma              Amy  2014        3

In [ ]:
# 전체 컬럼 이름 바꾸기
# df.columns = new_name_list